--DROP USER/LOGIN MARY

--SP_WHO


--USE [AdventureWorks2016CTP3]
--GO

--DROP USER [MARY]
--GO

--USE [master]
--GO

--DROP LOGIN [MARY]
--GO


USE [AdventureWorks2016CTP3]
GO

DROP  TABLE TABLEA
DROP  TABLE TABLEB

USE [AdventureWorks2016CTP3]
GO

CREATE TABLE TABLEA
(FN VARCHAR (10))

INSERT INTO  TABLEA VALUES ('BOB')

SELECT * FROM TABLEA

USE [AdventureWorks2016CTP3]
GO

CREATE TABLE TABLEB
(FN VARCHAR (10))

INSERT INTO  TABLEB VALUES ('LUCY')

SELECT * FROM TABLEB


--CREATE A SEPERATE USER AND LOGIN FOR TESTING.  MAKE SURE YOU SET THE AUTHENTICTION TO MIXED MODE

--USE [master]
--GO

--CREATE LOGIN [MARY] WITH PASSWORD=N'password', 
--DEFAULT_DATABASE=[master], 
--CHECK_EXPIRATION=OFF, 
--CHECK_POLICY=OFF
--GO

--USE [AdventureWorks2016CTP3]
--GO

--CREATE USER [MARY] FOR LOGIN [MARY]
--GO

--USE [AdventureWorks2016CTP3]
--GO

--ALTER ROLE [db_datawriter] ADD MEMBER [MARY]
--GO

--USE [AdventureWorks2016CTP3]
--GO

--ALTER ROLE [db_owner] ADD MEMBER [MARY]
--GO

--USER ADMIN ACQUIRE A LOCK ON TABLEA FROM BOB TO TOM

BEGIN TRAN
UPDATE TABLEA
SET FN = 'TOM'
WHERE FN = 'BOB'

SELECT * FROM TABLEA

--USER MARY EXECUTES AN UPDATE STATEMENT CAUSING AN EXCLUSIVE LOCK

--USE [AdventureWorks2016CTP3]
--GO

--BEGIN TRAN
--UPDATE TABLEB
--SET FN = 'SUSAN'
--WHERE FN = 'LUCY'

SELECT * FROM TABLEB

--OPEN TRANSACTIONS --SHOULD BE 2

SELECT spid,blocked,loginame,cmd,text,lastwaittype,physical_io,login_time,
open_tran,status,hostname
FROM SYS.SYSPROCESSES SP
CROSS APPLY SYS.DM_EXEC_SQL_TEXT(SP.[SQL_HANDLE])
AS DEST WHERE OPEN_TRAN >= 1

--UPDATE THE OTHER TABLE TABLEB

USE [AdventureWorks2016CTP3]
GO

BEGIN TRAN
UPDATE TABLEB
SET FN = 'SUSAN'
WHERE FN = 'LUCY'

SELECT * FROM TABLEB

--USE AdventureWorks2016CTP3
--GO

--BEGIN TRAN
--UPDATE TABLEA
--SET FN = 'BOB'
--WHERE FN = 'MATT'



--OPEN TRANSACTIONS

SELECT spid,blocked,loginame,cmd,text,lastwaittype,physical_io,login_time,
open_tran,status,hostname
FROM SYS.SYSPROCESSES SP
CROSS APPLY SYS.DM_EXEC_SQL_TEXT(SP.[SQL_HANDLE])
AS DEST WHERE OPEN_TRAN >= 1




