


--DROP  TABLE TABLEA

USE [AdventureWorks2016CTP3]
GO

CREATE TABLE TABLEA
(FN VARCHAR (10))

INSERT INTO  TABLEA VALUES ('BOB')

SELECT * FROM TABLEA

--USE [AdventureWorks2016CTP3]
--GO

--CREATE TABLE TABLEB
--(FN VARCHAR (10))

--INSERT INTO  TABLEA VALUES ('BOB')

--SELECT * FROM TABLEB

--USER 1 EXECUTES AN UPDATE STATEMENT CAUSING AN EXCLUSIVE LOCK, BUT NOT COMMITING THE TRANSACTION 

BEGIN TRAN
UPDATE TABLEA
SET FN = 'TOM'
WHERE FN = 'BOB'

COMMIT TRAN  --<< NOTE NOT COMMITING THE TRANSACTION. AS SUCH, THE LOCK IS NOT RELEASED


SELECT * FROM TABLEA


--NOW ANOTHER USER CALLED MARY TRIES TO UPDATE THE SAME TABLE WHILE THE TRANSACTION IS STILL OPEN 

--CREATE A SEPERATE USER AND LOGIN FOR TESTING.  MAKE SURE YOU SET THE AUTHENTICTION TO MIXED MODE

--USE [master]
--GO

--CREATE LOGIN [MARY] WITH PASSWORD=N'password', 
--DEFAULT_DATABASE=[master], 
--CHECK_EXPIRATION=OFF, 
--CHECK_POLICY=OFF
--GO

--USE [AdventureWorks2016CTP3]
--GO

--CREATE USER [MARY] FOR LOGIN [MARY]
--GO

--USE [AdventureWorks2016CTP3]
--GO

--ALTER ROLE [db_datawriter] ADD MEMBER [MARY]
--GO

--USE [AdventureWorks2016CTP3]
--GO

--ALTER ROLE [db_owner] ADD MEMBER [MARY]
--GO

--NOW LOG ON AS MARY AND EXECUTE THE UPDATE STATEMENT
--NOTICE THAT THE EXCUTION IS NOT STOPPING

USE AdventureWorks2016CTP3
GO

BEGIN TRAN
UPDATE TABLEA
SET FN = 'SAM'
WHERE FN = 'TOM'
COMMIT TRAN

--NOW COMMIT AND NOTICE THE RESULT.  SHOULD BE MARYS UPDATE TO SAM

BEGIN TRAN
UPDATE TABLEA
SET FN = 'TOM'
WHERE FN = 'BOB'

COMMIT TRAN  --<< NOTE NOT COMMITING THE TRANSACTION. AS SUCH, THE LOCK IS NOT RELEASED


--OPEN TRANSACTIONS

SELECT spid,blocked,loginame,cmd,text,lastwaittype,physical_io,login_time,
open_tran,status,hostname
FROM SYS.SYSPROCESSES SP
CROSS APPLY SYS.DM_EXEC_SQL_TEXT(SP.[SQL_HANDLE])
AS DEST WHERE OPEN_TRAN >= 1

SELECT * FROM TABLEA


