USE AdventureWorks2016CTP3
GO

DROP TABLE [AdventureWorks2016CTP3].[Person].[AddressB] 


--IMPORT DATA WITHOUT INDEXES TO VIEW SPACE USED

USE [AdventureWorks2016CTP3]
GO

SELECT *
INTO [AdventureWorks2016CTP3].[Person].[AddressB] 
FROM [AdventureWorks2016CTP3].[Person].[Address]

--LETS VIEW THE EXECUTION PLAN

--NOTICE THAT 82% OF THE COST IS TAKEN BY THE SORT COMMAND

SELECT City,AddressLine1
FROM [AdventureWorks2016CTP3].[Person].[AddressB] 
ORDER BY [City]  --<, WE ARE USING THE ORDER BY COMMAND (SORTING)


--SIMPLEST WAY TO AVOID A SORT OPERATOR IS TO CREATE A CLUSTERED INDEX

CREATE CLUSTERED INDEX [ClusteredIndex-20171026-165423] 
ON [Person].[AddressB]
([City]ASC)


--NOW LET REVIEW THE EXUECTION PLAN.  NOTICE THAT THERE IS NOT NEED TO SORT THE DATA AND THE SORT IS AVOIDED


SELECT City,AddressLine1
FROM [AdventureWorks2016CTP3].[Person].[AddressB] 
ORDER BY [City]  --<, WE ARE USING THE ORDER BY COMMAND (SORTING)





